before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format: zip
    files:
      - README.md
      - LICENSE
