before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos: [windows]
    goarch: [amd64]

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - config.yaml
      - README.md
      - LICENSE
